package com.say5.spark_evolve

import com.say5.spark_evolve.transform.{Aggregator, ParquetSink, Validator}
import org.apache.avro.Schema
import org.apache.avro.generic.{GenericData, GenericDatumWriter, GenericRecord}
import org.apache.avro.io.EncoderFactory
import org.apache.spark.sql.{DataFrame, SparkSession}
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types._

import java.io.ByteArrayOutputStream
import java.nio.file.{Files, Paths}
import scala.util.Random

/** In-process bench harness. Generates `n` synthetic Avro-encoded events, feeds them through the same
  * validator+aggregator chain the production pipeline uses, and writes Parquet to a local path. Reports
  * throughput, row count, file count, and total wall time.
  *
  * Decoupled from the Kafka source so it can be run without Docker. The end-to-end test in `src/it` covers
  * the Kafka → MinIO path with testcontainers.
  *
  * Args: <event-count> <output-dir>
  */
object BenchHarness {

  def main(args: Array[String]): Unit = {
    val eventCount = args.headOption.map(_.toInt).getOrElse(10000)
    val outDir     = args.lift(1).getOrElse("/tmp/spark-evolve-bench-out")
    val resultsDir = args.lift(2).getOrElse("bench/results")

    Files.createDirectories(Paths.get(outDir))
    Files.createDirectories(Paths.get(resultsDir))

    val schema = new Schema.Parser().parse(new java.io.File("schemas/orders/v2.avsc"))

    val spark = SparkSession
      .builder()
      .appName("spark-evolve-bench")
      .master(sys.env.getOrElse("SPARK_MASTER", "local[*]"))
      .config("spark.ui.enabled", "false")
      .config("spark.sql.shuffle.partitions", "8")
      .getOrCreate()
    spark.sparkContext.setLogLevel("ERROR")

    val totalStart = System.nanoTime()

    // Generate Kafka-like rows (topic, partition, offset, timestamp, value bytes).
    val genStart = System.nanoTime()
    val rows     = generateRows(spark, schema, eventCount)
    rows.persist()
    val rowCount   = rows.count()
    val genElapsed = System.nanoTime() - genStart

    // Run the validator on the generated bytes.
    val validateStart   = System.nanoTime()
    val split           = Validator.validate(rows, schema)
    val validCount      = split.valid.count()
    val badCount        = split.bad.count()
    val validateElapsed = System.nanoTime() - validateStart

    // Aggregate.
    val aggStart   = System.nanoTime()
    val agg        = Aggregator.aggregate(split.valid, "1 hour")
    val aggCount   = agg.count()
    val aggElapsed = System.nanoTime() - aggStart

    // Write Parquet.
    val writeStart = System.nanoTime()
    ParquetSink.writeAggregates(agg, outDir, coalesceTo = 4)
    val writeElapsed = System.nanoTime() - writeStart

    val totalElapsed = System.nanoTime() - totalStart

    val parquetFiles = listParquetFiles(Paths.get(outDir).toFile)
    val totalBytes   = parquetFiles.map(_.length()).sum
    val meanFileSize = if (parquetFiles.nonEmpty) totalBytes / parquetFiles.size else 0L

    val results = Map(
      "events"             -> rowCount,
      "valid_records"      -> validCount,
      "bad_records"        -> badCount,
      "aggregate_rows"     -> aggCount,
      "parquet_files"      -> parquetFiles.size.toLong,
      "parquet_bytes"      -> totalBytes,
      "mean_parquet_bytes" -> meanFileSize,
      "ms_generate"        -> nsToMs(genElapsed),
      "ms_validate"        -> nsToMs(validateElapsed),
      "ms_aggregate"       -> nsToMs(aggElapsed),
      "ms_write"           -> nsToMs(writeElapsed),
      "ms_total"           -> nsToMs(totalElapsed),
      "events_per_sec"     -> (rowCount * 1000L / math.max(1L, nsToMs(totalElapsed)))
    )

    val timestamp = java.time.LocalDateTime
      .now()
      .format(java.time.format.DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss"))
    val resultsPath = Paths.get(resultsDir).resolve(s"$timestamp.json")
    val json        = renderJson(results)
    Files.writeString(resultsPath, json)

    Console.out.println(formatTable(results))
    Console.out.println()
    Console.out.println(s"# results: $resultsPath")
    Console.out.println(s"# Local-machine numbers on the developer's workstation. See bench/README.md.")

    spark.stop()
  }

  private def generateRows(spark: SparkSession, schema: Schema, n: Int): DataFrame = {
    val baseTs         = java.time.Instant.parse("2026-01-01T00:00:00Z").toEpochMilli
    val partitionCount = math.min(8, math.max(1, n / 1000))
    val sc             = spark.sparkContext
    val rdd = sc
      .parallelize(0 until n, partitionCount)
      .mapPartitions { iter =>
        val rng = new Random(42)
        val w   = new GenericDatumWriter[GenericRecord](schema)
        iter.map { i =>
          val r = new GenericData.Record(schema)
          r.put("order_id", f"order-$i%010d")
          r.put("customer_id", f"customer-${rng.nextInt(1000)}%05d")
          val segments = Array("retail", "wholesale", "premium")
          r.put("customer_segment", segments(i % 3))
          r.put("total_cents", (rng.nextInt(50000) + 100).toLong)
          r.put("event_time", baseTs + (i.toLong * 13L))
          r.put("discount_cents", (rng.nextInt(500)).toLong)
          val out = new ByteArrayOutputStream(256)
          val enc = EncoderFactory.get().binaryEncoder(out, null)
          w.write(r, enc); enc.flush()
          val bytes: Array[Byte] = out.toByteArray
          (("orders": String), 0, i.toLong, new java.sql.Timestamp(baseTs + i.toLong * 13L), bytes)
        }
      }
    val sqlSchema = StructType(
      Array(
        StructField("topic", StringType, nullable = false),
        StructField("partition", IntegerType, nullable = false),
        StructField("offset", LongType, nullable = false),
        StructField("timestamp", TimestampType, nullable = false),
        StructField("value", BinaryType, nullable = false)
      )
    )
    val rowRdd = rdd.map { case (t, p, o, ts, v) =>
      org.apache.spark.sql.Row(t, p, o, ts, v)
    }
    spark.createDataFrame(rowRdd, sqlSchema).withColumn("key", lit(null).cast(BinaryType))
  }

  private def listParquetFiles(dir: java.io.File): List[java.io.File] = {
    if (!dir.exists() || !dir.isDirectory) Nil
    else {
      val out = List.newBuilder[java.io.File]
      def walk(d: java.io.File): Unit = {
        val files = Option(d.listFiles()).toList.flatten
        files.foreach { f =>
          if (f.isDirectory) walk(f)
          else if (f.getName.endsWith(".parquet")) out += f
        }
      }
      walk(dir)
      out.result()
    }
  }

  private def nsToMs(ns: Long): Long = ns / 1_000_000L

  private def renderJson(results: Map[String, Long]): String = {
    val entries = results.toSeq.sortBy(_._1)
    entries.map { case (k, v) => s"""  "$k": $v""" }.mkString("{\n", ",\n", "\n}\n")
  }

  private def formatTable(results: Map[String, Long]): String = {
    val rows = Seq(
      "events"             -> results("events").toString,
      "valid_records"      -> results("valid_records").toString,
      "bad_records"        -> results("bad_records").toString,
      "aggregate_rows"     -> results("aggregate_rows").toString,
      "parquet_files"      -> results("parquet_files").toString,
      "parquet_bytes"      -> results("parquet_bytes").toString,
      "mean_parquet_bytes" -> results("mean_parquet_bytes").toString,
      "ms_generate"        -> results("ms_generate").toString,
      "ms_validate"        -> results("ms_validate").toString,
      "ms_aggregate"       -> results("ms_aggregate").toString,
      "ms_write"           -> results("ms_write").toString,
      "ms_total"           -> results("ms_total").toString,
      "events_per_sec"     -> results("events_per_sec").toString
    )
    val keyW = rows.map(_._1.length).max
    val sb   = new StringBuilder
    sb.append("metric").append(" " * (keyW - 5)).append("  value\n")
    sb.append("-" * (keyW + 2 + 12)).append("\n")
    rows.foreach { case (k, v) =>
      sb.append(k).append(" " * (keyW - k.length)).append("  ").append(v).append("\n")
    }
    sb.toString
  }
}
