spark-evolve {
  kafka {
    bootstrap = "localhost:9092"
    bootstrap = ${?KAFKA_BOOTSTRAP}
    topic     = "orders"
    bad-topic = "orders-bad"
  }
  s3 {
    endpoint      = "http://localhost:9000"
    endpoint      = ${?S3_ENDPOINT}
    bucket        = "warehouse"
    output-prefix = "orders_hourly"
    bad-prefix    = "bad_records"
    access-key    = "minioadmin"
    access-key    = ${?S3_ACCESS_KEY}
    secret-key    = "minioadmin"
    secret-key    = ${?S3_SECRET_KEY}
    path-style    = true
  }
  schemas {
    dir           = "schemas"
    subject       = "orders"
    compatibility = "backward"
  }
  window {
    duration = "1 hour"
  }
}
